// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlwMJ-M6cXSZEVjzyRzNdPClU--NtYL6U',
    appId: '1:6763257958:web:3eef56a9fbe491e9b64da7',
    messagingSenderId: '6763257958',
    projectId: 'rct-app-dd771',
    authDomain: 'rct-app-dd771.firebaseapp.com',
    storageBucket: 'rct-app-dd771.firebasestorage.app',
    measurementId: 'G-Y569RSV80M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTCv4cexYolPqp4YgQSLcAtuUyTX1EJxQ',
    appId: '1:6763257958:android:d932118256f34f1ab64da7',
    messagingSenderId: '6763257958',
    projectId: 'rct-app-dd771',
    storageBucket: 'rct-app-dd771.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcqbXHnhwh4fSn_8Q_nhQpgqsd4jOxpC4',
    appId: '1:6763257958:ios:8a4673d7dff4092ab64da7',
    messagingSenderId: '6763257958',
    projectId: 'rct-app-dd771',
    storageBucket: 'rct-app-dd771.firebasestorage.app',
    iosBundleId: 'com.rct.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcqbXHnhwh4fSn_8Q_nhQpgqsd4jOxpC4',
    appId: '1:6763257958:ios:cabb48d7b9ba341eb64da7',
    messagingSenderId: '6763257958',
    projectId: 'rct-app-dd771',
    storageBucket: 'rct-app-dd771.firebasestorage.app',
    iosBundleId: 'com.example.rctApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlwMJ-M6cXSZEVjzyRzNdPClU--NtYL6U',
    appId: '1:6763257958:web:b690cfa8c2d0be08b64da7',
    messagingSenderId: '6763257958',
    projectId: 'rct-app-dd771',
    authDomain: 'rct-app-dd771.firebaseapp.com',
    storageBucket: 'rct-app-dd771.firebasestorage.app',
    measurementId: 'G-XVLB4JDL6Y',
  );
}
